spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    
---

spring:  
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

# H2 CLIENT
  h2:
    console:
      enabled: true
      path: /h2-console
      
# JPA, SQL
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true  